import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import { Bars3Icon } from '@heroicons/react/24/outline';

import Banner from '@/components/banner';
import Header from '@/components/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Palestine Info Hub',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="h-full" lang="en">
      <body className={`h-full ${inter.className}`}>
        <Header />
        <main className="relative bg-white">{children}</main>
      </body>
    </html>
  );
}
